### ISSUE TITLE
Fick type fel i hissen

### ISSUE THREAD

**Issue by JorgenLindell** [jomag/stuga2020#8]
Jag fick ett typfel när jag valde våning i hissen, testade med NÖDSTOPP först men blev uppmanad att inte använda det i onödan sen när jag tryckte 9 fick jag ett rött felmeddelande.
(Tror det var ungefär can't assign an int to a float array, tog tyvärr ingen kopia. Hoppas på att du har serverside loggning på såna fel... :) )

**Comment by mb3331** [comment]
Tryckte också 9 i hissen och fick nåt liknande: "Assigning value of type "float" to array of type "int" "

**Comment by jomag** [comment]
Detta, och ett antal problem relaterade till INPUT-hanteringen i hissen, är nu fixade.
